<?php
/*
 *	Made by Coldfire - https://coldfiredzn.com
 *
 *  Skyfall Template Variables
 */

$skyfall_local_version = "2.1.2";
$coldfire_url = "https://coldfiredzn.com";
$support_url = "https://coldfiredzn.com/discord";

$skyfall_settings_array = array(

    /* Setting name, then default value, then frontend var (if applicable) */

    array('logo_webp', '', 'THEME_LOGO_WEBP'),
    array('header_bg_webp', '/custom/templates/Skyfall/img/bg.webp', ''),
    array('pbg_webp', '', ''),
    array('ebg_webp', '/custom/templates/Skyfall/img/errorbg.webp', 'THEME_E_BG_WEBP'),
    array('lbg_webp', '/custom/templates/Skyfall/img/loginbg.webp', 'THEME_L_BG_WEBP'),
    array('rbg_webp', '/custom/templates/Skyfall/img/registerbg.webp', 'THEME_R_BG_WEBP'),
    array('navbar_size', 'medium', ''),
    array('particles', 'yes', ''),
    array('ext_update', 'yes', 'THEME_EXT_UPDATE'),
    array('custom_css', '', ''),
    array('header_bg', '/custom/templates/Skyfall/img/bg.jpg', ''),
    array('pbg', '', ''),
    array('logo', '', 'THEME_LOGO'),
    array('ts', 'icon', 'THEME_TS'),
    array('al', 'yes', 'THEME_AL'),
    array('links', 'gwh', ''),
    array('dark', 'yes', 'THEME_DARK'),
    array('card_rounded', 'yes', 'THEME_CARD_ROUNDED'),
    array('bg_height', '270px', ''),
    array('bg_height_m', '250px', ''),
    array('navbar', 'double', 'THEME_NAVBAR'),
    array('ebg', '/custom/templates/Skyfall/img/errorbg.jpg', 'THEME_E_BG'),
    array('lbg', '/custom/templates/Skyfall/img/loginbg.png', 'THEME_L_BG'),
    array('rbg', '/custom/templates/Skyfall/img/registerbg.jpg', 'THEME_R_BG'),
    array('elr_logo', '250px', 'THEME_ELR_LOGO'),
    array('elr_margin', '150px', 'THEME_ELR_MARGIN'),
    array('wb_s1', '003702b657a4445a955cfa7f24274e69', 'THEME_WB_S1'),
    array('wb_s2', '06440cef9a884036971298512c32a0f0', 'THEME_WB_S2'),
    array('wb_s3', 'c20e191bfe244416b94c70acf99ea327', 'THEME_WB_S3'),
    array('wb_s4', '106c04b856d74298bc0cbac6a35b47a0', 'THEME_WB_S4'),
    array('wb_s5', '1f1c1b59ecb3498a8d1125c2f69a8225', 'THEME_WB_S5'),
    array('wb_s6', 'e73d89adf8cb4b69b91d96594ae8585d', 'THEME_WB_S6'),
    array('wb_t', 'Welcome to Skyfall!', 'THEME_WB_T'),
    array('wb_d', 'To join our community, please login or register!', 'THEME_WB_D'),
    array('wb_1n', 'Login', 'THEME_WB_1N'),
    array('wb_1l', '/login', 'THEME_WB_1L'),
    array('wb_2n', 'Register', 'THEME_WB_2N'),
    array('wb_2l', '/register', 'THEME_WB_2L'),
    array('font', 'Montserrat', 'THEME_FONT'),
    array('p_color', '#326903', ''),
    array('logo_size', '200px', ''),
    array('logo_size_m', '180px', ''),
    array('coverlay', 'yes', 'THEME_C_OVERLAY'),
    array('portal_bg', 'custom/templates/Skyfall/img/portal-bg.png', 'THEME_PORTAL_BG'),
    array('portal1_icon', '/custom/templates/Skyfall/img/Forums.png', 'PORTAL_1_ICON'),
    array('portal2_icon', '/custom/templates/Skyfall/img/Vote.png', 'PORTAL_2_ICON'),
    array('portal3_icon', '/custom/templates/Skyfall/img/Shop.png', 'PORTAL_3_ICON'),
    array('portal1_link', '/forum', 'PORTAL_1_LINK'),
    array('portal2_link', '/vote', 'PORTAL_2_LINK'),
    array('portal3_link', 'https://store.hypixel.net', 'PORTAL_3_LINK'),
    array('portal_logo', '250px', 'PORTAL_LOGO_SIZE'),
    array('portal_logo_m', '200px', 'PORTAL_LOGO_SIZE_M'),
    array('portal_lm', '50px', 'PORTAL_LOGO_MARGIN'),
    array('portal_lmm', '25px', 'PORTAL_LOGO_MARGIN_M'),
    array('portal_im', '300px', 'PORTAL_IMAGE_MARGIN'),
    array('portal_imm', '250px', 'PORTAL_IMAGE_MARGIN_M'),
    array('ds_box', 'yes', 'THEME_DS_BOX'),
    array('about', 'Skyfall is a very cool NamelessMC template and this is an example description!', 'THEME_ABOUT'),
    array('other_t', 'Store', 'THEME_OTHER_T'),
    array('other_d', 'Visit our store today to check out some of the amazing items we have to offer!', 'THEME_OTHER_D'),
    array('other_bt', 'Visit Store', 'THEME_OTHER_BT'),
    array('other_bl', 'https://store.hypixel.net', 'THEME_OTHER_BL'),
    array('news_btn', 'yes', 'THEME_NEWS_BTN'),
    array('news_link', '/forum/view/28-news/', 'THEME_NEWS_LINK'),
    array('discord_server', '(Insert url here)', 'THEME_DISCORD_SERVER'),
    array('slider1_title', '', 'THEME_SLIDER1_TITLE'),
    array('slider1_desc', 'Configure this slider in StaffCP -> Skyfall', 'THEME_SLIDER1_DESCRIPTION'),
    array('slider1_image', '/custom/templates/Skyfall/img/slider.jpg', 'THEME_SLIDER1_IMAGE'),
    array('slider1_link', 'https://coldfiredzn.com', 'THEME_SLIDER1_LINK'),
    array('slider2_title', 'Slider #2', 'THEME_SLIDER2_TITLE'),
    array('slider2_desc', 'Configure this slider in StaffCP -> Skyfall', 'THEME_SLIDER2_DESCRIPTION'),
    array('slider2_image', '/custom/templates/Skyfall/img/slider.jpg', 'THEME_SLIDER2_IMAGE'),
    array('slider2_link', 'https://coldfiredzn.com', 'THEME_SLIDER2_LINK'),
    array('slider3_title', 'Slider #3', 'THEME_SLIDER3_TITLE'),
    array('slider3_desc', 'Configure this slider in StaffCP -> Skyfall', 'THEME_SLIDER3_DESCRIPTION'),
    array('slider3_image', '/custom/templates/Skyfall/img/slider.jpg', 'THEME_SLIDER3_IMAGE'),
    array('slider3_link', 'https://coldfiredzn.com', 'THEME_SLIDER3_LINK'),
    array('slider4_title', 'Slider #4', 'THEME_SLIDER4_TITLE'),
    array('slider4_desc', 'Configure this slider in StaffCP -> Skyfall', 'THEME_SLIDER4_DESCRIPTION'),
    array('slider4_image', '/custom/templates/Skyfall/img/slider.jpg', 'THEME_SLIDER4_IMAGE'),
    array('slider4_link', 'https://coldfiredzn.com', 'THEME_SLIDER4_LINK'),
    array('slider5_title', 'Slider #5', 'THEME_SLIDER5_TITLE'),
    array('slider5_desc', 'Configure this slider in StaffCP -> Skyfall', 'THEME_SLIDER5_DESCRIPTION'),
    array('slider5_image', '/custom/templates/Skyfall/img/slider.jpg', 'THEME_SLIDER5_IMAGE'),
    array('slider5_link', 'https://coldfiredzn.com', 'THEME_SLIDER5_LINK'),
    array('slider1_link_open', 'no', 'THEME_SLIDER1_LINK_OPEN'),
    array('slider2_link_open', 'no', 'THEME_SLIDER2_LINK_OPEN'),
    array('slider3_link_open', 'no', 'THEME_SLIDER3_LINK_OPEN'),
    array('slider4_link_open', 'no', 'THEME_SLIDER4_LINK_OPEN'),
    array('slider5_link_open', 'no', 'THEME_SLIDER5_LINK_OPEN')
);