<?php
/*
 *	Made by Coldfire - https://coldfiredzn.com
 *
 *  Cobalt Template Variables
 */

$cobalt_local_version = "1.6.7";
$coldfire_url = "https://coldfiredzn.com";
$support_url = "https://coldfiredzn.com/discord";

$cobalt_settings_array = [

    /* Setting name, then default value, then frontend var (if applicable) */

    ['winter', 'no', 'THEME_WINTER'],
    ['webp_compression', '75', ''],
    ['custom_js', '', 'THEME_CUSTOM_JS'],
    ['custom_js_scripts', '', 'THEME_CUSTOM_JS_SCRIPTS'],
    ['custom_css_styles', '', 'THEME_CUSTOM_CSS_STYLES'],
    ['blur_header_bg', 'no', 'THEME_BLUR_HEADER_BG'],
    ['mc_server', 'mc.hypixel.net', 'THEME_MC_SERVER'],
    ['discord_server_id', '682657813406941204', ''],
    ['store_url', 'https://store.hypixel.net', 'THEME_STORE_URL'],
    ['style_store_link', 'yes', 'THEME_STYLE_STORE_LINK'],
    ['header_bg_position', 'top', ''],
    ['navbar_offset', '-15px', ''],
    ['navbar_alignment', 'center', 'THEME_NAVBAR_ALIGNMENT'],
    ['coverlay_opacity', '0.6', 'THEME_C_OVERLAY_OPACITY'],
    ['loading_animation', 'yes', 'THEME_LOADING_ANIMATION'],
    ['lr_modal_image', 'no', 'THEME_LR_MODAL_IMAGE'],
    ['lr_coverlay', 'no', 'THEME_LR_COVERLAY'],
    ['lr_coverlay_opacity', '0.5', 'THEME_LR_COVERLAY_OPACITY'],
    ['footer_size', 'large', 'THEME_FOOTER_SIZE'],
    ['other_bi', '<i class="fas fa-shopping-cart"></i>', 'THEME_OTHER_BI'],
    ['play_t', 'Play Now', 'THEME_PLAY_T'],
    ['play_d', 'Start your journey today! Join the server now to play the best bedwars, skywars, and more!', 'THEME_PLAY_D'],
    ['play_b', 'yes', 'THEME_PLAY_B'],
    ['update_notif', 'yes', 'THEME_UPDATE_NOTIF'],
    ['loader_color', '#FFFFFF', ''],
    ['enable_slider', 'no', 'THEME_ENABLE_SLIDER'],
    ['enable_slider2', 'yes', 'THEME_ENABLE_SLIDER2'],
    ['enable_slider3', 'yes', 'THEME_ENABLE_SLIDER3'],
    ['enable_slider4', 'yes', 'THEME_ENABLE_SLIDER4'],
    ['enable_slider5', 'yes', 'THEME_ENABLE_SLIDER5'],
    ['nav_store_glow', 'yes', 'THEME_NAV_STORE_GLOW'],
    ['header_bg_shading', '0.4', 'THEME_HEADER_BG_SHADING'],
    ['ds_breakpoint', '1050px', ''],
    ['slider_height', '250px', ''],
    ['slider_height_m', '150px', ''],
    ['vote_rewards', 'Voting Rewards: 2 epic crate keys for each vote!', 'THEME_VOTE_REWARDS'],
    ['settings_backup_1', '', ''],
    ['settings_backup_2', '', ''],
    ['settings_backup_3', '', ''],
    ['backup_1_timestamp', '', ''],
    ['backup_2_timestamp', '', ''],
    ['backup_3_timestamp', '', ''],
    ['ext_update', 'yes', 'THEME_EXT_UPDATE'],
    ['serve_lib_cdn', 'yes', 'THEME_SERVE_LIB_CDN'],
    ['news_btn', 'yes', 'THEME_NEWS_BTN'],
    ['news_link', '/forum/view/2-forum/', 'THEME_NEWS_LINK'],
    ['ds_box', 'yes', 'THEME_DS_BOX'],
    ['al', 'no', 'THEME_AL'],
    ['logo', '', 'THEME_LOGO'],
    ['logo_webp', '', 'THEME_LOGO_WEBP'],
    ['particles', 'yes', ''],
    ['p_color', '#1684A2', ''],
    ['discord_server', '(Insert url here]', 'THEME_DISCORD_SERVER'],
    ['bg_height', '475px', ''],
    ['navbar', 'top', 'THEME_NAVBAR'],
    ['custom_css', '', ''],
    ['coverlay', 'yes', 'THEME_C_OVERLAY'],
    ['wb_t', 'Welcome to Cobalt!', 'THEME_WB_T'],
    ['wb_d', 'To join our community, please login or register!', 'THEME_WB_D'],
    ['wb_skin_id', '8223f53ee9430528', 'THEME_WB_SKIN_ID'],
    ['lbg', '', 'THEME_L_BG'],
    ['rbg', '', 'THEME_R_BG'],
    ['lbg_webp', '', 'THEME_L_BG_WEBP'],
    ['rbg_webp', '', 'THEME_R_BG_WEBP'],
    ['header_bg', '', 'THEME_HEADER_BG'],
    ['header_bg_webp', '', ''],
    ['other_t', 'Store', 'THEME_OTHER_T'],
    ['other_d', 'Check out our store to purchase ranks, crate keys, and more!', 'THEME_OTHER_D'],
    ['other_bt', 'Shop Now', 'THEME_OTHER_BT'],
    ['other_bl', 'https://store.hypixel.net', 'THEME_OTHER_BL'],
    ['logo_size', '200px', ''],
    ['slider1_title', 'Slider #1', 'THEME_SLIDER1_TITLE'],
    ['slider1_desc', 'Configure this slider in StaffCP -> Cobalt', 'THEME_SLIDER1_DESCRIPTION'],
    ['slider1_image', '', 'THEME_SLIDER1_IMAGE'],
    ['slider1_link', 'https://coldfiredzn.com', 'THEME_SLIDER1_LINK'],
    ['slider2_title', 'Slider #2', 'THEME_SLIDER2_TITLE'],
    ['slider2_desc', 'Configure this slider in StaffCP -> Cobalt', 'THEME_SLIDER2_DESCRIPTION'],
    ['slider2_image', '', 'THEME_SLIDER2_IMAGE'],
    ['slider2_link', 'https://coldfiredzn.com', 'THEME_SLIDER2_LINK'],
    ['slider3_title', 'Slider #3', 'THEME_SLIDER3_TITLE'],
    ['slider3_desc', 'Configure this slider in StaffCP -> Cobalt', 'THEME_SLIDER3_DESCRIPTION'],
    ['slider3_image', '', 'THEME_SLIDER3_IMAGE'],
    ['slider3_link', 'https://coldfiredzn.com', 'THEME_SLIDER3_LINK'],
    ['slider4_title', 'Slider #4', 'THEME_SLIDER4_TITLE'],
    ['slider4_desc', 'Configure this slider in StaffCP -> Cobalt', 'THEME_SLIDER4_DESCRIPTION'],
    ['slider4_image', '', 'THEME_SLIDER4_IMAGE'],
    ['slider4_link', 'https://coldfiredzn.com', 'THEME_SLIDER4_LINK'],
    ['slider5_title', 'Slider #5', 'THEME_SLIDER5_TITLE'],
    ['slider5_desc', 'Configure this slider in StaffCP -> Cobalt', 'THEME_SLIDER5_DESCRIPTION'],
    ['slider5_image', '', 'THEME_SLIDER5_IMAGE'],
    ['slider5_link', 'https://coldfiredzn.com', 'THEME_SLIDER5_LINK'],
    ['slider1_link_open', 'no', 'THEME_SLIDER1_LINK_OPEN'],
    ['slider2_link_open', 'no', 'THEME_SLIDER2_LINK_OPEN'],
    ['slider3_link_open', 'no', 'THEME_SLIDER3_LINK_OPEN'],
    ['slider4_link_open', 'no', 'THEME_SLIDER4_LINK_OPEN'],
    ['slider5_link_open', 'no', 'THEME_SLIDER5_LINK_OPEN'],
    ['slider1_image_webp', '', 'THEME_SLIDER1_IMAGE_WEBP'],
    ['slider2_image_webp', '', 'THEME_SLIDER2_IMAGE_WEBP'],
    ['slider3_image_webp', '', 'THEME_SLIDER3_IMAGE_WEBP'],
    ['slider4_image_webp', '', 'THEME_SLIDER4_IMAGE_WEBP'],
    ['slider5_image_webp', '', 'THEME_SLIDER5_IMAGE_WEBP'],
    ['portal_color_overlay', 'yes', ''],
    ['portal_ds_texts', 'yes', 'PORTAL_DS_TEXTS'],
    ['portal_color_overlay_opacity', '0.7', ''],
    ['portal_enable_fourth_icon', 'yes', 'PORTAL_ENABLE_FOURTH_ICON'],
    ['portal1_icon_webp', '', 'PORTAL_1_ICON_WEBP'],
    ['portal2_icon_webp', '', 'PORTAL_2_ICON_WEBP'],
    ['portal3_icon_webp', '', 'PORTAL_3_ICON_WEBP'],
    ['portal4_icon_webp', '', 'PORTAL_4_ICON_WEBP'],
    ['portal_bg_webp', '', 'PORTAL_BG_WEBP'],
    ['portal_particles', 'yes', 'PORTAL_PARTICLES'],
    ['portal_bg', '', 'PORTAL_BG'],
    ['portal1_name', 'Forums', 'PORTAL_1_NAME'],
    ['portal2_name', 'Store', 'PORTAL_2_NAME'],
    ['portal3_name', 'Vote', 'PORTAL_3_NAME'],
    ['portal4_name', 'Bans', 'PORTAL_4_NAME'],
    ['portal1_icon', '', 'PORTAL_1_ICON'],
    ['portal2_icon', '', 'PORTAL_2_ICON'],
    ['portal3_icon', '', 'PORTAL_3_ICON'],
    ['portal4_icon', '', 'PORTAL_4_ICON'],
    ['portal1_fa_icon', '<i class="fas fa-comments"></i>', 'PORTAL_1_FA_ICON'],
    ['portal2_fa_icon', '<i class="fas fa-star"></i>', 'PORTAL_2_FA_ICON'],
    ['portal3_fa_icon', '<i class="fas fa-thumbs-up"></i>', 'PORTAL_3_FA_ICON'],
    ['portal4_fa_icon', '<i class="fas fa-ban"></i>', 'PORTAL_4_FA_ICON'],
    ['portal1_link', '/forum', 'PORTAL_1_LINK'],
    ['portal2_link', 'https://store.hypixel.net', 'PORTAL_2_LINK'],
    ['portal3_link', '/vote', 'PORTAL_3_LINK'],
    ['portal4_link', '/bans', 'PORTAL_4_LINK'],
    ['portal_icon_width', '100%', 'PORTAL_ICON_WIDTH'],
    ['portal_fa_icons', 'no', 'PORTAL_FA_ICONS'],
    ['portal_icon_names', 'no', 'PORTAL_ICON_NAMES'],
    ['portal_im', '-55vh', 'PORTAL_IMAGE_MARGIN'],
    ['bg_height_m', '340px', ''],
    ['logo_size_m', '130px', ''],
    ['portal_imm', '30vh', 'PORTAL_IMAGE_MARGIN_M'],
    ['portal_icon_width_m', '70%', 'PORTAL_ICON_WIDTH_M'],
    ['full_body_avatars', 'yes', 'THEME_FULL_BODY_AVATARS'],
    ['store_box_img', '', 'THEME_STORE_BOX_IMG'],
    ['store_box_img_webp', '', 'THEME_STORE_BOX_IMG_WEBP'],
    ['store_box_title', 'Store', 'THEME_STORE_BOX_TITLE'],
    ['store_box_subtitle', 'Shop now!', 'THEME_STORE_BOX_SUBTITLE'],
    ['store_box_icon', '<i class="fas fa-shopping-basket"></i>', 'THEME_STORE_BOX_ICON'],
    ['store_box_link', '/store', 'THEME_STORE_BOX_LINK'],
    ['store_box_enable', 'yes', 'THEME_STORE_BOX_ENABLE'],
    ['rules_home_icon', '<i class="fas fa-home"></i>', 'THEME_RULES_HOME_ICON'],
    ['rules_fa_icons', 'yes', 'THEME_RULES_FA_ICONS'],
    ['vote_rewards_icon', '', 'THEME_VOTE_REWARDS_ICON'],
    ['vote_rewards_icon_webp', '', 'THEME_VOTE_REWARDS_ICON_WEBP']
];